name: Deploy
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Deploy
              uses: redkubes/docusaurus-deploy-action@master
              with:
                source-folder: ./
                git-user: myyerrol
                git-password: ${{ secrets.GITHUB_TOKEN }}
                deployment-branch: gh-pages
