name: Deploy
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Config docs
              uses: actions/checkout@master
              with:
                repository: "microdynamics-cpu/backend-design-tutorial"
                path: docs
            - name: test
              run: |
                ls
                cd docs
                ls
            - name: Deploy
              uses: redkubes/docusaurus-deploy-action@master
              with:
                source-folder: ./
                git-user: myyerrol
                git-password: ${{ secrets.GITHUB_TOKEN }}
                deployment-branch: gh-pages
